import type { DashboardData } from "@/lib/types";

export const demoDashboardData: DashboardData = {
  mode: "demo",
  config: {
    geminiApiKey: "AIza-demo-key-redacted",
    n8nWebhookUrl: "https://n8n.local/webhook/redditpulse-manual",
    defaultFetchLimit: 10,
    defaultSourceLimit: 4,
  },
  subreddits: [
    {
      id: "sub-1",
      name: "rantandventph",
      enabled: true,
      processImages: true,
      createdAt: "2026-04-22T07:05:00.000Z",
    },
    {
      id: "sub-2",
      name: "offmychest",
      enabled: true,
      processImages: false,
      createdAt: "2026-04-22T07:06:00.000Z",
    },
    {
      id: "sub-3",
      name: "mildlyinfuriating",
      enabled: false,
      processImages: true,
      createdAt: "2026-04-22T07:07:00.000Z",
    },
  ],
  runs: [
    {
      id: "run-2",
      status: "succeeded",
      sourceListing: "hot",
      triggeredAt: "2026-04-22T08:35:00.000Z",
      completedAt: "2026-04-22T08:39:00.000Z",
      totalSubreddits: 2,
      notes:
        "Engagement-first curation kept each subreddit to one digest with four cited sources.",
      digests: [
        {
          id: "digest-1",
          subredditId: "sub-1",
          subredditName: "rantandventph",
          headline: "Relationship screenshot posts pushed confrontation and family stress to the top.",
          summary:
            "The latest digest from r/rantandventph clustered around private-message screenshots, controlling partners, and home pressure spilling into public vent posts. Gemini used image context on the strongest screenshot-heavy threads, but the final card still stayed text-first and grounded the summary in four linked posts.",
          imageContextUsed: true,
          sourceCount: 4,
          sources: [
            {
              id: "source-1",
              title: "Hindi ko na alam kung valid pa ba 'tong galit ko",
              author: "taglishthrowaway",
              permalink: "https://reddit.com/r/rantandventph/comments/demo1",
              score: 512,
              commentCount: 63,
              previewImageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
              isImagePost: true,
              sortRank: 1,
            },
            {
              id: "source-2",
              title: "Parents keep comparing me to my siblings",
              author: "manilamidnight",
              permalink: "https://reddit.com/r/rantandventph/comments/demo2",
              score: 401,
              commentCount: 41,
              previewImageUrl: null,
              isImagePost: false,
              sortRank: 2,
            },
            {
              id: "source-3",
              title: "Screenshots of a breakup that should have stayed private",
              author: "burnerforventing",
              permalink: "https://reddit.com/r/rantandventph/comments/demo3",
              score: 356,
              commentCount: 27,
              previewImageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4",
              isImagePost: true,
              sortRank: 3,
            },
            {
              id: "source-4",
              title: "Working all week tapos ako pa rin ang masama",
              author: "quietcommute",
              permalink: "https://reddit.com/r/rantandventph/comments/demo4",
              score: 274,
              commentCount: 18,
              previewImageUrl: null,
              isImagePost: false,
              sortRank: 4,
            },
          ],
        },
        {
          id: "digest-2",
          subredditId: "sub-2",
          subredditName: "offmychest",
          headline: "Workplace resentment and late-boundary breaking dominated the latest confession cycle.",
          summary:
            "r/offmychest skewed toward work exhaustion, friends crossing boundaries, and people burning out while trying to look composed in public. The digest stayed text-only because the selected threads already carried enough body text to support a coherent paragraph without spending image budget.",
          imageContextUsed: false,
          sourceCount: 4,
          sources: [
            {
              id: "source-5",
              title: "I am tired of always being the calm one",
              author: "stillholdingit",
              permalink: "https://reddit.com/r/offmychest/comments/demo5",
              score: 890,
              commentCount: 144,
              previewImageUrl: null,
              isImagePost: false,
              sortRank: 1,
            },
            {
              id: "source-6",
              title: "My friend keeps sharing my secrets as jokes",
              author: "cornersofsleep",
              permalink: "https://reddit.com/r/offmychest/comments/demo6",
              score: 645,
              commentCount: 88,
              previewImageUrl: null,
              isImagePost: false,
              sortRank: 2,
            },
            {
              id: "source-7",
              title: "I can't tell whether I'm angry or just exhausted",
              author: "nightdeskworker",
              permalink: "https://reddit.com/r/offmychest/comments/demo7",
              score: 514,
              commentCount: 71,
              previewImageUrl: null,
              isImagePost: false,
              sortRank: 3,
            },
            {
              id: "source-8",
              title: "My boss congratulated me after making me work through the weekend",
              author: "latetrainhome",
              permalink: "https://reddit.com/r/offmychest/comments/demo8",
              score: 472,
              commentCount: 53,
              previewImageUrl: null,
              isImagePost: false,
              sortRank: 4,
            },
          ],
        },
      ],
    },
  ],
};
